services:
    app.admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Users' }

    app.admin.role:
        class: AppBundle\Admin\RoleAdmin
        arguments: [~, AppBundle\Entity\Role, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Roles' }

    app.admin.blog_post:
        class: AppBundle\Admin\BlogPostAdmin
        arguments: [~, AppBundle\Entity\BlogPost, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Blog Post' }

    app.twig.blog_post_extension:
        class: AppBundle\Twig\BlogPostExtension
        tags:
            - { name: twig.extension }
